// client/components/system-info/SystemInfoScreen.svelte
<script lang="ts">
  /**
   * SystemInfoScreen Component
   *
   * Screen for displaying system information (git version, Claude Code version).
   *
   * Features:
   * - Fetches system info from API on mount
   * - Displays version information for installed tools
   * - Loading, error, and empty states
   */

  interface ModelUsageStats {
    readonly inputTokens: number;
    readonly outputTokens: number;
    readonly cacheReadInputTokens: number;
    readonly cacheCreationInputTokens: number;
  }

  interface DailyActivity {
    readonly date: string;
    readonly messageCount?: number;
    readonly sessionCount?: number;
    readonly toolCallCount?: number;
    readonly tokensByModel?: Record<string, number>;
  }

  interface ClaudeCodeUsage {
    readonly totalSessions: number;
    readonly totalMessages: number;
    readonly firstSessionDate: string | null;
    readonly lastComputedDate: string | null;
    readonly modelUsage: Record<string, ModelUsageStats>;
    readonly recentDailyActivity: DailyActivity[];
  }

  interface SystemInfo {
    readonly git: {
      readonly version: string | null;
      readonly error: string | null;
    };
    readonly claudeCode: {
      readonly version: string | null;
      readonly error: string | null;
    };
    readonly models: {
      readonly promptModel: string;
      readonly assistantModel: string;
    };
    readonly claudeCodeUsage: ClaudeCodeUsage | null;
  }

  /**
   * Component state
   */
  let systemInfo = $state<SystemInfo | null>(null);
  let loading = $state(true);
  let error = $state<string | null>(null);

  /**
   * Helper functions
   */
  function formatNumber(n: number): string {
    if (n >= 1_000_000_000) return `${(n / 1_000_000_000).toFixed(1)}B`;
    if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(1)}M`;
    if (n >= 1_000) return `${(n / 1_000).toFixed(1)}K`;
    return n.toString();
  }

  function formatDate(dateStr: string): string {
    try {
      const d = new Date(dateStr);
      return d.toLocaleDateString(undefined, {
        year: "numeric",
        month: "short",
        day: "numeric",
      });
    } catch {
      return dateStr;
    }
  }

  function getModelShortName(modelId: string): string {
    if (modelId.includes("opus-4-6")) return "Opus 4.6";
    if (modelId.includes("opus-4-5")) return "Opus 4.5";
    if (modelId.includes("sonnet-4-5")) return "Sonnet 4.5";
    if (modelId.includes("haiku")) return "Haiku";
    return modelId;
  }

  function getSortedActivity(activities: DailyActivity[]): DailyActivity[] {
    return [...activities].sort((a, b) => b.date.localeCompare(a.date));
  }

  function getDailyTokenTotal(activity: DailyActivity): number {
    if (activity.tokensByModel === undefined) return 0;
    return Object.values(activity.tokensByModel).reduce((sum, t) => sum + t, 0);
  }

  function getTotalRecentTokens(activities: DailyActivity[]): number {
    return activities.reduce((sum, a) => sum + getDailyTokenTotal(a), 0);
  }

  /**
   * Fetch system info from the server
   */
  async function fetchSystemInfo(): Promise<void> {
    try {
      loading = true;
      error = null;
      const resp = await fetch("/api/system-info");
      if (!resp.ok) {
        throw new Error(`Failed to fetch system info: ${resp.status}`);
      }
      const data = (await resp.json()) as SystemInfo;
      systemInfo = data;
    } catch (e) {
      error = e instanceof Error ? e.message : "Failed to load system info";
      console.error("Failed to fetch system info:", e);
    } finally {
      loading = false;
    }
  }

  /**
   * Load system info on mount
   */
  $effect(() => {
    void fetchSystemInfo();
  });
</script>

<div
  class="system-info-screen flex flex-col h-full bg-bg-primary"
  role="main"
  aria-label="System information"
>
  <!-- Header -->
  <div class="px-4 py-3 border-b border-border-default bg-bg-secondary">
    <h2 class="text-lg font-semibold text-text-primary">System Information</h2>
  </div>

  <!-- Content Area -->
  <div class="flex-1 overflow-y-auto px-4 py-4">
    {#if loading}
      <!-- Loading State -->
      <div
        class="flex items-center justify-center py-12"
        role="status"
        aria-live="polite"
      >
        <svg
          class="animate-spin h-6 w-6 text-accent-fg"
          xmlns="http://www.w3.org/2000/svg"
          fill="none"
          viewBox="0 0 24 24"
          aria-hidden="true"
        >
          <circle
            class="opacity-25"
            cx="12"
            cy="12"
            r="10"
            stroke="currentColor"
            stroke-width="4"
          />
          <path
            class="opacity-75"
            fill="currentColor"
            d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
          />
        </svg>
        <span class="ml-2 text-sm text-text-secondary"
          >Loading system information...</span
        >
      </div>
    {:else if error !== null}
      <!-- Error State -->
      <div class="flex flex-col items-center justify-center py-12 text-center">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="48"
          height="48"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="1.5"
          stroke-linecap="round"
          stroke-linejoin="round"
          class="text-danger-fg mb-4"
          aria-hidden="true"
        >
          <circle cx="12" cy="12" r="10" />
          <line x1="12" y1="8" x2="12" y2="12" />
          <line x1="12" y1="16" x2="12.01" y2="16" />
        </svg>
        <p class="text-text-secondary mb-2">{error}</p>
        <button
          type="button"
          onclick={() => void fetchSystemInfo()}
          class="px-4 py-2 text-sm font-medium
                 bg-bg-secondary hover:bg-bg-hover text-text-primary
                 border border-border-default rounded-lg
                 transition-colors
                 focus:outline-none focus:ring-2 focus:ring-accent-emphasis"
        >
          Retry
        </button>
      </div>
    {:else if systemInfo !== null}
      <!-- System Info Display -->
      <div class="space-y-4 max-w-2xl">
        <!-- Git -->
        <div
          class="rounded-lg border border-border-default bg-bg-secondary p-4"
        >
          <div class="flex items-start gap-3">
            <div class="flex-1">
              <h3 class="text-sm font-semibold text-text-primary mb-1">Git</h3>
              {#if systemInfo.git.version !== null}
                <p class="text-sm text-success-fg font-mono">
                  {systemInfo.git.version}
                </p>
              {:else if systemInfo.git.error !== null}
                <p class="text-sm text-danger-fg">
                  {systemInfo.git.error}
                </p>
              {:else}
                <p class="text-sm text-text-tertiary">
                  Version information not available
                </p>
              {/if}
            </div>
          </div>
        </div>

        <!-- Claude Code -->
        <div
          class="rounded-lg border border-border-default bg-bg-secondary p-4"
        >
          <div class="flex items-start gap-3">
            <div class="flex-1">
              <h3 class="text-sm font-semibold text-text-primary mb-1">
                Claude Code
              </h3>
              {#if systemInfo.claudeCode.version !== null}
                <p class="text-sm text-success-fg font-mono">
                  {systemInfo.claudeCode.version}
                </p>
              {:else if systemInfo.claudeCode.error !== null}
                <p class="text-sm text-danger-fg">
                  {systemInfo.claudeCode.error}
                </p>
              {:else}
                <p class="text-sm text-text-tertiary">
                  Version information not available
                </p>
              {/if}
            </div>
          </div>
        </div>

        <!-- Models -->
        <div
          class="rounded-lg border border-border-default bg-bg-secondary p-4"
        >
          <div class="flex-1">
            <h3 class="text-sm font-semibold text-text-primary mb-3">Models</h3>
            <div class="space-y-2">
              <div class="flex items-center justify-between">
                <span class="text-sm text-text-secondary">Prompt Model</span>
                <span class="text-sm text-text-primary font-mono">
                  {systemInfo.models.promptModel}
                </span>
              </div>
              <div class="flex items-center justify-between">
                <span class="text-sm text-text-secondary">Assistant Model</span>
                <span class="text-sm text-text-primary font-mono">
                  {systemInfo.models.assistantModel}
                </span>
              </div>
            </div>
          </div>
        </div>

        <!-- Claude Code Usage -->
        {#if systemInfo.claudeCodeUsage !== null}
          <div
            class="rounded-lg border border-border-default bg-bg-secondary p-4"
          >
            <div class="flex-1">
              <h3 class="text-sm font-semibold text-text-primary mb-3">
                Claude Code Usage
              </h3>

              <!-- Overview Stats -->
              <div class="space-y-2 mb-4 pb-4 border-b border-border-default">
                <div class="flex items-center justify-between">
                  <span class="text-sm text-text-secondary">Total Sessions</span
                  >
                  <span
                    class="text-sm text-text-primary font-mono tabular-nums"
                  >
                    {formatNumber(systemInfo.claudeCodeUsage.totalSessions)}
                  </span>
                </div>
                <div class="flex items-center justify-between">
                  <span class="text-sm text-text-secondary">Total Messages</span
                  >
                  <span
                    class="text-sm text-text-primary font-mono tabular-nums"
                  >
                    {formatNumber(systemInfo.claudeCodeUsage.totalMessages)}
                  </span>
                </div>
                <div class="flex items-center justify-between">
                  <span class="text-sm text-text-secondary"
                    >Total Tokens (14 Days)</span
                  >
                  <span
                    class="text-sm text-text-primary font-mono tabular-nums"
                  >
                    {formatNumber(
                      getTotalRecentTokens(
                        systemInfo.claudeCodeUsage.recentDailyActivity,
                      ),
                    )}
                  </span>
                </div>
                {#if systemInfo.claudeCodeUsage.firstSessionDate !== null}
                  <div class="flex items-center justify-between">
                    <span class="text-sm text-text-secondary"
                      >First Session</span
                    >
                    <span class="text-sm text-text-primary font-mono">
                      {formatDate(systemInfo.claudeCodeUsage.firstSessionDate)}
                    </span>
                  </div>
                {/if}
                {#if systemInfo.claudeCodeUsage.lastComputedDate !== null}
                  <div class="flex items-center justify-between">
                    <span class="text-sm text-text-secondary"
                      >Last Computed</span
                    >
                    <span class="text-sm text-text-primary font-mono">
                      {formatDate(systemInfo.claudeCodeUsage.lastComputedDate)}
                    </span>
                  </div>
                {/if}
              </div>

              <!-- Model Usage -->
              {#if Object.keys(systemInfo.claudeCodeUsage.modelUsage).length > 0}
                <div class="mb-4 pb-4 border-b border-border-default">
                  <h4 class="text-sm font-semibold text-text-primary mb-2">
                    Model Usage
                  </h4>
                  <div class="space-y-3">
                    {#each Object.entries(systemInfo.claudeCodeUsage.modelUsage) as [modelId, stats]}
                      <div class="space-y-1">
                        <div class="text-sm font-medium text-text-primary">
                          {getModelShortName(modelId)}
                        </div>
                        <div class="grid grid-cols-2 gap-2 text-xs">
                          <div class="flex justify-between">
                            <span class="text-text-secondary">Input:</span>
                            <span
                              class="text-text-primary font-mono tabular-nums"
                              >{formatNumber(stats.inputTokens)}</span
                            >
                          </div>
                          <div class="flex justify-between">
                            <span class="text-text-secondary">Output:</span>
                            <span
                              class="text-text-primary font-mono tabular-nums"
                              >{formatNumber(stats.outputTokens)}</span
                            >
                          </div>
                          <div class="flex justify-between">
                            <span class="text-text-secondary">Cache Read:</span>
                            <span
                              class="text-text-primary font-mono tabular-nums"
                              >{formatNumber(stats.cacheReadInputTokens)}</span
                            >
                          </div>
                          <div class="flex justify-between">
                            <span class="text-text-secondary">Cache Write:</span
                            >
                            <span
                              class="text-text-primary font-mono tabular-nums"
                              >{formatNumber(
                                stats.cacheCreationInputTokens,
                              )}</span
                            >
                          </div>
                        </div>
                      </div>
                    {/each}
                  </div>
                </div>
              {/if}

              <!-- Recent Activity -->
              {#if systemInfo.claudeCodeUsage.recentDailyActivity.length > 0}
                <div>
                  <h4 class="text-sm font-semibold text-text-primary mb-2">
                    Recent Activity (Last 14 Days)
                  </h4>
                  <div class="overflow-x-auto">
                    <table class="w-full text-xs">
                      <thead>
                        <tr class="border-b border-border-default">
                          <th
                            class="text-left py-2 pr-4 text-text-secondary font-medium"
                            >Date</th
                          >
                          <th
                            class="text-right py-2 px-2 text-text-secondary font-medium"
                            >Messages</th
                          >
                          <th
                            class="text-right py-2 px-2 text-text-secondary font-medium"
                            >Sessions</th
                          >
                          <th
                            class="text-right py-2 px-2 text-text-secondary font-medium"
                            >Tool Calls</th
                          >
                          <th
                            class="text-right py-2 pl-2 text-text-secondary font-medium"
                            >Tokens</th
                          >
                        </tr>
                      </thead>
                      <tbody>
                        {#each getSortedActivity(systemInfo.claudeCodeUsage.recentDailyActivity) as activity}
                          <tr class="border-b border-border-default/50">
                            <td class="py-2 pr-4 text-text-primary font-mono">
                              {formatDate(activity.date)}
                            </td>
                            <td
                              class="py-2 px-2 text-right text-text-primary font-mono tabular-nums"
                            >
                              {activity.messageCount ?? 0}
                            </td>
                            <td
                              class="py-2 px-2 text-right text-text-primary font-mono tabular-nums"
                            >
                              {activity.sessionCount ?? 0}
                            </td>
                            <td
                              class="py-2 px-2 text-right text-text-primary font-mono tabular-nums"
                            >
                              {activity.toolCallCount ?? 0}
                            </td>
                            <td
                              class="py-2 pl-2 text-right text-text-primary font-mono tabular-nums"
                            >
                              {formatNumber(getDailyTokenTotal(activity))}
                            </td>
                          </tr>
                        {/each}
                      </tbody>
                    </table>
                  </div>
                </div>
              {/if}
            </div>
          </div>
        {/if}
      </div>
    {/if}
  </div>
</div>

// client/src/features/system-info/SystemInfoScreen.tsx
import { createSignal, For, type JSX, onMount, Show } from "solid-js";
import { createSystemInfoApiClient } from "../../../../client-shared/src/api/system-info";
import type {
  ClaudeCodeUsage,
  SystemInfo,
  VersionInfo,
} from "../../../../src/types/system-info";
import { ScreenHeader } from "../../components/ScreenHeader";
import {
  formatCompactNumber,
  formatSystemInfoDate,
  getRecentTokenTotal,
  getSortedSystemInfoActivity,
  getSystemInfoModelShortName,
} from "./presentation";

export interface SystemInfoScreenProps {
  readonly apiBaseUrl: string;
}

const SCREEN_SHELL_CLASS =
  "mx-auto flex h-full max-w-7xl flex-col gap-6 px-4 py-6 sm:px-6";
const PANEL_CLASS =
  "rounded-2xl border border-border-default bg-bg-secondary p-5";
const METRIC_PANEL_CLASS =
  "rounded-2xl border border-border-default bg-bg-secondary/80 p-4";
const STATUS_PANEL_CLASS =
  "rounded-2xl border border-border-default bg-bg-primary/60 p-4";
const LOADING_DOT_CLASS =
  "h-2 w-2 animate-pulse rounded-full bg-accent-emphasis";

function getVersionToneClass(versionInfo: VersionInfo): string {
  if (versionInfo.version !== null) {
    return "border-success-emphasis/30 bg-success-muted/10";
  }

  if (versionInfo.error !== null) {
    return "border-danger-emphasis/30 bg-danger-muted/10";
  }

  return "border-border-default bg-bg-primary/60";
}

function getVersionValueClass(versionInfo: VersionInfo): string {
  if (versionInfo.version !== null) {
    return "text-success-fg";
  }

  if (versionInfo.error !== null) {
    return "text-danger-fg";
  }

  return "text-text-tertiary";
}

function renderToolVersionCard(
  label: string,
  description: string,
  versionInfo: VersionInfo,
): JSX.Element {
  return (
    <article class={`${PANEL_CLASS} ${getVersionToneClass(versionInfo)}`}>
      <div class="flex items-start justify-between gap-4">
        <div class="space-y-2">
          <div>
            <p class="text-[11px] font-semibold uppercase tracking-[0.22em] text-text-tertiary">
              Tool
            </p>
            <h3 class="mt-1 text-base font-semibold text-text-primary">
              {label}
            </h3>
          </div>
          <p class="text-sm leading-6 text-text-secondary">{description}</p>
        </div>
        <span
          class={`rounded-full border px-3 py-1 text-[11px] font-semibold uppercase tracking-wide ${
            versionInfo.version !== null
              ? "border-success-emphasis/30 bg-success-muted/15 text-success-fg"
              : versionInfo.error !== null
                ? "border-danger-emphasis/30 bg-danger-muted/15 text-danger-fg"
                : "border-border-default bg-bg-primary text-text-tertiary"
          }`}
        >
          {versionInfo.version !== null
            ? "Available"
            : versionInfo.error !== null
              ? "Error"
              : "Unknown"}
        </span>
      </div>
      <p
        class={`mt-4 break-all rounded-xl border border-border-default/60 bg-bg-primary/60 px-3 py-2 font-mono text-sm ${getVersionValueClass(
          versionInfo,
        )}`}
      >
        {versionInfo.version ??
          versionInfo.error ??
          "Version information is not available in this environment."}
      </p>
    </article>
  );
}

function renderUsageSummary(
  label: string,
  usage: ClaudeCodeUsage | null,
): JSX.Element {
  if (usage === null) {
    return (
      <section class={PANEL_CLASS}>
        <div class="flex items-center justify-between gap-3">
          <div>
            <p class="text-[11px] font-semibold uppercase tracking-[0.22em] text-text-tertiary">
              Usage
            </p>
            <h3 class="mt-1 text-lg font-semibold text-text-primary">
              {label}
            </h3>
          </div>
          <span class="rounded-full border border-border-default bg-bg-primary px-3 py-1 text-[11px] font-semibold uppercase tracking-wide text-text-tertiary">
            Unavailable
          </span>
        </div>
        <p class="mt-4 text-sm leading-6 text-text-secondary">
          {label} usage data is not available in this environment.
        </p>
      </section>
    );
  }

  const sortedActivity = getSortedSystemInfoActivity(usage.recentDailyActivity);
  const modelUsageEntries = Object.entries(usage.modelUsage);

  return (
    <section class={`${PANEL_CLASS} space-y-5`}>
      <div class="flex flex-wrap items-start justify-between gap-3">
        <div>
          <p class="text-[11px] font-semibold uppercase tracking-[0.22em] text-text-tertiary">
            Usage
          </p>
          <h3 class="mt-1 text-lg font-semibold text-text-primary">{label}</h3>
        </div>
        <Show when={usage.firstSessionDate !== null}>
          <span class="rounded-full border border-border-default bg-bg-primary px-3 py-1 text-xs text-text-secondary">
            First session {formatSystemInfoDate(usage.firstSessionDate ?? "")}
          </span>
        </Show>
      </div>

      <div class="grid grid-cols-1 gap-3 md:grid-cols-3">
        <div class={METRIC_PANEL_CLASS}>
          <p class="text-[11px] uppercase tracking-wide text-text-tertiary">
            Sessions
          </p>
          <p class="mt-2 text-2xl font-semibold text-text-primary">
            {formatCompactNumber(usage.totalSessions)}
          </p>
        </div>
        <div class={METRIC_PANEL_CLASS}>
          <p class="text-[11px] uppercase tracking-wide text-text-tertiary">
            Messages
          </p>
          <p class="mt-2 text-2xl font-semibold text-text-primary">
            {formatCompactNumber(usage.totalMessages)}
          </p>
        </div>
        <div class={METRIC_PANEL_CLASS}>
          <p class="text-[11px] uppercase tracking-wide text-text-tertiary">
            Recent Tokens
          </p>
          <p class="mt-2 text-2xl font-semibold text-text-primary">
            {formatCompactNumber(getRecentTokenTotal(usage))}
          </p>
        </div>
      </div>

      <div class="grid grid-cols-1 gap-4 xl:grid-cols-[minmax(0,1.35fr)_minmax(0,1fr)]">
        <div class={`${STATUS_PANEL_CLASS} space-y-3`}>
          <div>
            <h4 class="text-sm font-semibold text-text-primary">
              Recent activity
            </h4>
            <p class="mt-1 text-xs leading-5 text-text-secondary">
              Latest daily session activity captured from the local usage
              dataset.
            </p>
          </div>
          <Show
            when={sortedActivity.length > 0}
            fallback={
              <p class="text-sm text-text-secondary">
                No recent activity has been recorded yet.
              </p>
            }
          >
            <div class="space-y-2">
              <For each={sortedActivity.slice(0, 7)}>
                {(activity) => (
                  <div class="flex flex-col gap-2 rounded-xl border border-border-default/60 bg-bg-secondary px-3 py-3 sm:flex-row sm:items-center sm:justify-between">
                    <div>
                      <p class="text-sm font-medium text-text-primary">
                        {formatSystemInfoDate(activity.date)}
                      </p>
                      <p class="mt-1 text-xs text-text-secondary">
                        {activity.messageCount !== undefined
                          ? `${formatCompactNumber(activity.messageCount)} messages`
                          : "No message data"}
                        {activity.toolCallCount !== undefined
                          ? ` | ${formatCompactNumber(activity.toolCallCount)} tool calls`
                          : ""}
                      </p>
                    </div>
                    <Show when={activity.tokensByModel !== undefined}>
                      <span class="rounded-full border border-accent-emphasis/30 bg-accent-muted/10 px-3 py-1 text-xs font-medium text-accent-fg">
                        {formatCompactNumber(
                          Object.values(activity.tokensByModel ?? {}).reduce(
                            (sum, tokenCount) => sum + tokenCount,
                            0,
                          ),
                        )}{" "}
                        tokens
                      </span>
                    </Show>
                  </div>
                )}
              </For>
            </div>
          </Show>
        </div>

        <div class={`${STATUS_PANEL_CLASS} space-y-3`}>
          <div>
            <h4 class="text-sm font-semibold text-text-primary">Model usage</h4>
            <p class="mt-1 text-xs leading-5 text-text-secondary">
              Token totals grouped by reported model identifier.
            </p>
          </div>
          <Show
            when={modelUsageEntries.length > 0}
            fallback={
              <p class="text-sm text-text-secondary">
                No model usage has been recorded yet.
              </p>
            }
          >
            <div class="space-y-2">
              <For each={modelUsageEntries}>
                {([modelId, modelUsage]) => (
                  <div class="rounded-xl border border-border-default/60 bg-bg-secondary px-3 py-3">
                    <div class="flex items-start justify-between gap-3">
                      <div>
                        <p class="text-sm font-medium text-text-primary">
                          {getSystemInfoModelShortName(modelId)}
                        </p>
                        <p class="mt-1 break-all text-xs text-text-tertiary">
                          {modelId}
                        </p>
                      </div>
                      <span class="rounded-full border border-border-default bg-bg-primary px-3 py-1 text-[11px] text-text-secondary">
                        {formatCompactNumber(
                          modelUsage.inputTokens + modelUsage.outputTokens,
                        )}{" "}
                        total
                      </span>
                    </div>
                    <div class="mt-3 grid grid-cols-2 gap-2 text-xs text-text-secondary">
                      <div class="rounded-lg bg-bg-primary px-3 py-2">
                        In: {formatCompactNumber(modelUsage.inputTokens)}
                      </div>
                      <div class="rounded-lg bg-bg-primary px-3 py-2">
                        Out: {formatCompactNumber(modelUsage.outputTokens)}
                      </div>
                    </div>
                  </div>
                )}
              </For>
            </div>
          </Show>
        </div>
      </div>
    </section>
  );
}

export function SystemInfoScreen(props: SystemInfoScreenProps): JSX.Element {
  const systemInfoApi = createSystemInfoApiClient({
    apiBaseUrl: props.apiBaseUrl,
  });
  const [systemInfo, setSystemInfo] = createSignal<SystemInfo | null>(null);
  const [isLoading, setIsLoading] = createSignal(true);
  const [errorMessage, setErrorMessage] = createSignal<string | null>(null);

  async function load(): Promise<void> {
    setIsLoading(true);
    setErrorMessage(null);

    try {
      setSystemInfo(await systemInfoApi.fetchSystemInfo());
    } catch (error) {
      setErrorMessage(
        error instanceof Error ? error.message : "Failed to load system info",
      );
    } finally {
      setIsLoading(false);
    }
  }

  onMount(() => {
    void load();
  });

  return (
    <section class={SCREEN_SHELL_CLASS}>
      <ScreenHeader
        title="System Information"
        subtitle="Runtime availability, configured models, and recent Claude Code or Codex usage for the current QraftBox environment."
      />

      <Show when={isLoading()}>
        <div class="flex min-h-[320px] flex-col items-center justify-center gap-4 rounded-2xl border border-border-default bg-bg-secondary text-text-secondary">
          <div class="flex gap-2">
            <span class={LOADING_DOT_CLASS} />
            <span class={`${LOADING_DOT_CLASS} [animation-delay:120ms]`} />
            <span class={`${LOADING_DOT_CLASS} [animation-delay:240ms]`} />
          </div>
          <p class="text-sm">Loading system information...</p>
        </div>
      </Show>

      <Show when={errorMessage() !== null}>
        <div class="rounded-2xl border border-danger-emphasis/40 bg-danger-muted/10 p-6">
          <p class="text-sm font-medium text-danger-fg">{errorMessage()}</p>
          <button
            type="button"
            class="mt-4 rounded-md border border-danger-emphasis/40 bg-bg-primary px-3 py-2 text-sm font-medium text-text-primary transition hover:bg-bg-hover"
            onClick={() => void load()}
          >
            Retry
          </button>
        </div>
      </Show>

      <Show
        when={!isLoading() && errorMessage() === null && systemInfo() !== null}
      >
        <>
          <div class="grid grid-cols-1 gap-4 xl:grid-cols-[minmax(0,1.35fr)_minmax(0,1fr)]">
            <div class="grid grid-cols-1 gap-4 lg:grid-cols-3">
              {renderToolVersionCard(
                "Git",
                "Repository plumbing and diff operations used across project views.",
                systemInfo()!.git,
              )}
              {renderToolVersionCard(
                "Claude Code",
                "CLI runtime availability for Claude-backed coding and review sessions.",
                systemInfo()!.claudeCode,
              )}
              {renderToolVersionCard(
                "Codex",
                "CLI runtime availability for Codex-backed coding and review sessions.",
                systemInfo()!.codexCode,
              )}
            </div>

            <section class={`${PANEL_CLASS} space-y-4`}>
              <div>
                <p class="text-[11px] font-semibold uppercase tracking-[0.22em] text-text-tertiary">
                  Active models
                </p>
                <h3 class="mt-1 text-lg font-semibold text-text-primary">
                  Default bindings
                </h3>
              </div>
              <div class="space-y-3">
                <div class={STATUS_PANEL_CLASS}>
                  <p class="text-[11px] uppercase tracking-wide text-text-tertiary">
                    Prompt model
                  </p>
                  <p class="mt-2 break-all font-mono text-sm text-text-primary">
                    {systemInfo()!.models.promptModel}
                  </p>
                </div>
                <div class={STATUS_PANEL_CLASS}>
                  <p class="text-[11px] uppercase tracking-wide text-text-tertiary">
                    Assistant model
                  </p>
                  <p class="mt-2 break-all font-mono text-sm text-text-primary">
                    {systemInfo()!.models.assistantModel}
                  </p>
                </div>
              </div>
            </section>
          </div>

          {renderUsageSummary("Claude Code", systemInfo()!.claudeCodeUsage)}
          {renderUsageSummary("Codex", systemInfo()!.codexCodeUsage)}
        </>
      </Show>
    </section>
  );
}
