// client/components/terminal/TerminalScreen.svelte
<script lang="ts">
  import { onDestroy, onMount, tick } from "svelte";
  import { Terminal } from "@xterm/xterm";
  import { FitAddon } from "@xterm/addon-fit";
  import "@xterm/xterm/css/xterm.css";

  const {
    contextId,
  }: {
    contextId: string;
  } = $props();

  type ConnectResponse = {
    sessionId: string;
    websocketPath: string;
    websocketUrl?: string;
    reused?: boolean;
  };

  type StatusResponse =
    | { hasSession: false }
    | {
        hasSession: true;
        sessionId: string;
        websocketPath: string;
        websocketUrl?: string;
      };

  type ServerMessage =
    | { type: "output"; data: string }
    | { type: "exit"; code: number }
    | { type: "error"; message: string }
    | { type: "pong" };

  type TerminalDimensions = {
    rows: number;
    cols: number;
  };

  let terminalHost = $state<HTMLDivElement | undefined>(undefined);
  let terminalInstance = $state<Terminal | null>(null);
  let fitAddon = $state<FitAddon | null>(null);
  let webSocket = $state<WebSocket | null>(null);

  let isConnecting = $state(false);
  let isConnected = $state(false);
  let connectionError = $state<string | null>(null);
  let activeSessionId = $state<string | null>(null);
  let lastContextId = $state(contextId);
  let checkingExistingSession = $state(false);
  let terminalContainer = $state<HTMLDivElement | undefined>(undefined);
  let terminalHeightPx = $state<number | null>(null);
  let isPhoneViewport = $state(false);

  function detectPhoneViewport(): boolean {
    return window.innerWidth <= 768;
  }

  function buildWebSocketUrl(
    websocketPath: string,
    websocketUrl?: string,
  ): string {
    if (websocketUrl !== undefined && websocketUrl.length > 0) {
      return websocketUrl;
    }
    const protocol = window.location.protocol === "https:" ? "wss:" : "ws:";
    return `${protocol}//${window.location.host}${websocketPath}`;
  }

  function disposeTerminalResources(): void {
    if (webSocket !== null) {
      webSocket.onopen = null;
      webSocket.onmessage = null;
      webSocket.onerror = null;
      webSocket.onclose = null;
      if (
        webSocket.readyState === WebSocket.OPEN ||
        webSocket.readyState === WebSocket.CONNECTING
      ) {
        webSocket.close();
      }
      webSocket = null;
    }

    if (terminalInstance !== null) {
      terminalInstance.dispose();
      terminalInstance = null;
    }

    fitAddon = null;
    isConnecting = false;
    isConnected = false;
    activeSessionId = null;
  }

  function ensureTerminalInitialized(): void {
    if (terminalInstance !== null || terminalHost === undefined) {
      return;
    }

    const createdTerminal = new Terminal({
      convertEol: false,
      cursorBlink: true,
      fontFamily: "ui-monospace, SFMono-Regular, Menlo, Consolas, monospace",
      fontSize: 13,
      scrollback: 5000,
      theme: {
        background: "#0f172a",
        foreground: "#e2e8f0",
        cursor: "#93c5fd",
      },
    });

    const createdFitAddon = new FitAddon();
    createdTerminal.loadAddon(createdFitAddon);
    createdTerminal.open(terminalHost);
    createdFitAddon.fit();

    createdTerminal.onData((typedData) => {
      if (webSocket !== null && webSocket.readyState === WebSocket.OPEN) {
        webSocket.send(
          JSON.stringify({
            type: "input",
            data: typedData,
          }),
        );
      }
    });

    terminalInstance = createdTerminal;
    fitAddon = createdFitAddon;
  }

  function focusTerminal(): void {
    terminalInstance?.focus();
  }

  function sendResize(dimensions: TerminalDimensions): void {
    if (webSocket === null || webSocket.readyState !== WebSocket.OPEN) {
      return;
    }
    webSocket.send(
      JSON.stringify({
        type: "resize",
        rows: dimensions.rows,
        cols: dimensions.cols,
      }),
    );
  }

  function fitAndResizeTerminal(): void {
    if (fitAddon === null || terminalInstance === null) {
      return;
    }
    fitAddon.fit();
    const dimensions = fitAddon.proposeDimensions();
    if (dimensions !== undefined) {
      sendResize(dimensions);
    }
  }

  function getMaxTerminalHeightPx(): number {
    const minHeightPx = isPhoneViewport ? 180 : 260;
    if (terminalContainer === undefined) {
      return Math.max(minHeightPx, Math.floor(window.innerHeight * 0.8));
    }
    const reservedSpacePx = isPhoneViewport ? 28 : 88;
    return Math.max(
      minHeightPx,
      terminalContainer.clientHeight - reservedSpacePx,
    );
  }

  function clampTerminalHeight(heightPx: number): number {
    const minHeightPx = isPhoneViewport ? 180 : 260;
    return Math.max(minHeightPx, Math.min(getMaxTerminalHeightPx(), heightPx));
  }

  function ensureTerminalHeight(): void {
    if (terminalHeightPx !== null) {
      return;
    }
    const initialRatio = isPhoneViewport ? 0.96 : 0.75;
    terminalHeightPx = clampTerminalHeight(
      Math.floor(getMaxTerminalHeightPx() * initialRatio),
    );
  }

  function resizeTerminalHeight(deltaPx: number): void {
    ensureTerminalHeight();
    if (terminalHeightPx === null) {
      return;
    }
    terminalHeightPx = clampTerminalHeight(terminalHeightPx + deltaPx);
    requestAnimationFrame(() => {
      fitAndResizeTerminal();
    });
  }

  function maximizeTerminalHeight(): void {
    terminalHeightPx = getMaxTerminalHeightPx();
    requestAnimationFrame(() => {
      fitAndResizeTerminal();
    });
  }

  function resetTerminalHeight(): void {
    terminalHeightPx = null;
    ensureTerminalHeight();
    requestAnimationFrame(() => {
      fitAndResizeTerminal();
    });
  }

  function handleServerMessage(serverMessage: ServerMessage): void {
    if (terminalInstance === null) {
      return;
    }

    if (serverMessage.type === "output") {
      terminalInstance.write(serverMessage.data);
      return;
    }

    if (serverMessage.type === "exit") {
      terminalInstance.writeln(
        `\r\n\r\n[terminal exited with code ${serverMessage.code}]`,
      );
      isConnected = false;
      activeSessionId = null;
      return;
    }

    if (serverMessage.type === "error") {
      terminalInstance.writeln(`\r\n[error] ${serverMessage.message}`);
      connectionError = serverMessage.message;
    }
  }

  async function connect(): Promise<void> {
    if (isConnecting || isConnected) {
      return;
    }

    isConnecting = true;
    connectionError = null;

    try {
      const response = await fetch(`/api/ctx/${contextId}/terminal/connect`, {
        method: "POST",
      });

      if (!response.ok) {
        const errorData = (await response.json()) as { error?: string };
        throw new Error(
          errorData.error ?? `Failed to connect terminal (${response.status})`,
        );
      }

      const connectResponse = (await response.json()) as ConnectResponse;
      activeSessionId = connectResponse.sessionId;

      await tick();
      ensureTerminalInitialized();

      if (terminalInstance === null) {
        throw new Error("Terminal UI could not be initialized");
      }

      terminalInstance.reset();
      terminalInstance.writeln(
        `[connected to ${contextId} in ${new Date().toLocaleTimeString()}]`,
      );

      const createdWebSocket = new WebSocket(
        buildWebSocketUrl(
          connectResponse.websocketPath,
          connectResponse.websocketUrl,
        ),
      );

      createdWebSocket.onopen = () => {
        isConnecting = false;
        isConnected = true;
        fitAndResizeTerminal();
        focusTerminal();
      };

      createdWebSocket.onmessage = (event) => {
        try {
          const serverMessage = JSON.parse(event.data) as ServerMessage;
          handleServerMessage(serverMessage);
        } catch {
          // Ignore invalid frames from server.
        }
      };

      createdWebSocket.onerror = () => {
        connectionError = "Terminal WebSocket error";
      };

      createdWebSocket.onclose = () => {
        isConnecting = false;
        isConnected = false;
        activeSessionId = null;
      };

      webSocket = createdWebSocket;
    } catch (error) {
      isConnecting = false;
      isConnected = false;
      activeSessionId = null;
      connectionError =
        error instanceof Error ? error.message : "Terminal connection failed";
    }
  }

  async function tryResumeExistingSession(): Promise<void> {
    if (isConnecting || isConnected || checkingExistingSession) {
      return;
    }

    checkingExistingSession = true;
    try {
      const response = await fetch(`/api/ctx/${contextId}/terminal/status`);
      if (!response.ok) {
        return;
      }
      const status = (await response.json()) as StatusResponse;
      if (status.hasSession) {
        await connect();
      }
    } catch {
      // Ignore status check failures.
    } finally {
      checkingExistingSession = false;
    }
  }

  function disconnect(): void {
    if (isConnecting) {
      return;
    }
    void (async () => {
      try {
        await fetch(`/api/ctx/${contextId}/terminal/disconnect`, {
          method: "POST",
        });
      } catch {
        // Ignore network errors; client resources will still be cleaned up.
      } finally {
        disposeTerminalResources();
        connectionError = null;
      }
    })();
  }

  $effect(() => {
    if (contextId !== lastContextId) {
      lastContextId = contextId;
      disposeTerminalResources();
      connectionError = null;
      void tryResumeExistingSession();
    }
  });

  onMount(() => {
    const updateViewport = (): void => {
      isPhoneViewport = detectPhoneViewport();
    };
    updateViewport();
    window.addEventListener("resize", updateViewport);
    void tryResumeExistingSession();
    return () => {
      window.removeEventListener("resize", updateViewport);
    };
  });

  $effect(() => {
    if (isConnected && fitAddon !== null) {
      ensureTerminalHeight();
      const resizeHandler = (): void => {
        if (terminalHeightPx !== null) {
          terminalHeightPx = clampTerminalHeight(terminalHeightPx);
        }
        fitAndResizeTerminal();
      };

      window.addEventListener("resize", resizeHandler);
      return () => {
        window.removeEventListener("resize", resizeHandler);
      };
    }
  });

  onDestroy(() => {
    disposeTerminalResources();
  });
</script>

<main class="terminal-screen flex-1 min-h-0 bg-bg-primary">
  <div class="h-full w-full p-2 sm:p-6">
    {#if !isConnected && !isConnecting}
      <div class="h-full w-full flex items-center justify-center">
        <div class="text-center">
          <button
            type="button"
            class="px-4 py-2 text-sm font-medium rounded-md
                   bg-accent-emphasis text-white hover:opacity-90 transition-opacity"
            onclick={() => void connect()}
          >
            connect
          </button>
          {#if connectionError !== null}
            <p class="mt-3 text-sm text-danger-fg">{connectionError}</p>
          {/if}
        </div>
      </div>
    {:else}
      <div
        class="h-full w-full flex flex-col gap-2"
        bind:this={terminalContainer}
      >
        <div class="flex justify-end gap-2 flex-wrap">
          <button
            type="button"
            class="px-2 py-1.5 text-xs font-medium rounded-md border border-border-default
                   bg-bg-secondary text-text-primary hover:bg-bg-tertiary transition-colors"
            onclick={() => {
              resizeTerminalHeight(120);
            }}
          >
            +
          </button>
          <button
            type="button"
            class="px-2 py-1.5 text-xs font-medium rounded-md border border-border-default
                   bg-bg-secondary text-text-primary hover:bg-bg-tertiary transition-colors"
            onclick={() => {
              resizeTerminalHeight(-120);
            }}
          >
            -
          </button>
          <button
            type="button"
            class="px-2 py-1.5 text-xs font-medium rounded-md border border-border-default
                   bg-bg-secondary text-text-primary hover:bg-bg-tertiary transition-colors"
            onclick={maximizeTerminalHeight}
          >
            max
          </button>
          <button
            type="button"
            class="px-2 py-1.5 text-xs font-medium rounded-md border border-border-default
                   bg-bg-secondary text-text-primary hover:bg-bg-tertiary transition-colors"
            onclick={resetTerminalHeight}
          >
            reset
          </button>
          <button
            type="button"
            class="px-3 py-1.5 text-xs font-medium rounded-md border border-border-default
                   bg-bg-secondary text-text-primary hover:bg-bg-tertiary transition-colors
                   disabled:opacity-50 disabled:cursor-not-allowed"
            onclick={disconnect}
            disabled={isConnecting}
          >
            disconnect
          </button>
        </div>
        <div
          class="shrink-0 min-h-0 w-full rounded-md border border-border-default overflow-hidden bg-slate-900"
          style={`height: ${terminalHeightPx ?? (isPhoneViewport ? Math.floor(window.innerHeight * 0.55) : 480)}px;`}
          onclick={focusTerminal}
          onkeydown={focusTerminal}
          role="button"
          tabindex="0"
        >
          <div
            bind:this={terminalHost}
            class="terminal-host h-full w-full"
          ></div>
        </div>
      </div>
      {#if activeSessionId !== null}
        <p class="mt-2 text-xs text-text-tertiary">
          session: {activeSessionId}
        </p>
      {/if}
    {/if}
  </div>
</main>

<style>
  .terminal-host :global(.xterm) {
    height: 100%;
    padding: 0.75rem;
  }

  .terminal-host :global(.xterm-viewport) {
    scrollbar-width: thin;
  }
</style>

// client/src/features/terminal/TerminalScreen.tsx
import { FitAddon } from "@xterm/addon-fit";
import { Terminal } from "@xterm/xterm";
import "@xterm/xterm/css/xterm.css";
import { createEffect, createSignal, onCleanup, onMount, Show } from "solid-js";
import type { JSX } from "solid-js";
import {
  createTerminalApiClient,
  type TerminalConnectResponse,
} from "../../../../client-shared/src/api/terminal";
import { ScreenHeader } from "../../components/ScreenHeader";
import { ToolbarIconButton } from "../../components/ToolbarIconButton";
import { buildTerminalWebSocketUrl, parseTerminalServerMessage } from "./state";

export interface TerminalScreenProps {
  readonly apiBaseUrl: string;
  readonly contextId: string | null;
}

interface TerminalDimensions {
  readonly rows: number;
  readonly cols: number;
}

const DEFAULT_TERMINAL_HEIGHT = 480;
const PHONE_TERMINAL_HEIGHT_RATIO = 0.55;
const PHONE_INITIAL_HEIGHT_RATIO = 0.96;
const DESKTOP_INITIAL_HEIGHT_RATIO = 0.75;
const PHONE_MIN_TERMINAL_HEIGHT = 160;
const DESKTOP_MIN_TERMINAL_HEIGHT = 220;

function detectPhoneViewport(): boolean {
  return window.innerWidth <= 768;
}

function nextAnimationFrame(): Promise<void> {
  return new Promise((resolve) => {
    window.requestAnimationFrame(() => {
      resolve();
    });
  });
}

export function TerminalScreen(props: TerminalScreenProps): JSX.Element {
  const terminalApi = createTerminalApiClient({
    apiBaseUrl: props.apiBaseUrl,
  });

  const [isCheckingStatus, setIsCheckingStatus] = createSignal(false);
  const [isConnecting, setIsConnecting] = createSignal(false);
  const [isConnected, setIsConnected] = createSignal(false);
  const [connectionError, setConnectionError] = createSignal<string | null>(
    null,
  );
  const [activeSessionId, setActiveSessionId] = createSignal<string | null>(
    null,
  );
  const [isPhoneViewport, setIsPhoneViewport] = createSignal(false);
  const [terminalHeightPx, setTerminalHeightPx] = createSignal<number | null>(
    null,
  );

  let activeSocket: WebSocket | null = null;
  let activeContextId: string | null = null;
  let terminalInstance: Terminal | null = null;
  let fitAddon: FitAddon | null = null;
  let terminalHostRef: HTMLDivElement | undefined;
  let terminalContainerRef: HTMLDivElement | undefined;
  let terminalControlsRef: HTMLDivElement | undefined;
  let terminalResizeHandleRef: HTMLDivElement | undefined;
  let terminalSessionMetaRef: HTMLParagraphElement | undefined;
  let isResizingTerminal = false;
  let terminalDragStartY = 0;
  let terminalDragStartHeightPx = 0;
  let lastObservedContextId: string | null | undefined = undefined;
  let pendingTerminalOutputChunks: string[] = [];

  function disposeSocket(): void {
    if (activeSocket === null) {
      return;
    }

    activeSocket.onopen = null;
    activeSocket.onmessage = null;
    activeSocket.onerror = null;
    activeSocket.onclose = null;
    if (
      activeSocket.readyState === WebSocket.OPEN ||
      activeSocket.readyState === WebSocket.CONNECTING
    ) {
      activeSocket.close();
    }
    activeSocket = null;
  }

  function stopTerminalResizeDrag(): void {
    isResizingTerminal = false;
    document.body.style.cursor = "";
    document.body.style.userSelect = "";
    window.removeEventListener("mousemove", handleTerminalResizeMouseMove);
    window.removeEventListener("mouseup", handleTerminalResizeMouseUp);
  }

  function disposeTerminalResources(): void {
    stopTerminalResizeDrag();
    disposeSocket();

    terminalInstance?.dispose();
    terminalInstance = null;
    fitAddon = null;
    pendingTerminalOutputChunks = [];

    setIsCheckingStatus(false);
    setIsConnecting(false);
    setIsConnected(false);
    setActiveSessionId(null);
    setTerminalHeightPx(null);
  }

  function hostHasMountedTerminal(): boolean {
    return terminalHostRef?.querySelector(".xterm") !== null;
  }

  function ensureTerminalInitialized(): void {
    if (terminalHostRef === undefined) {
      return;
    }

    if (terminalInstance !== null && hostHasMountedTerminal()) {
      return;
    }

    if (terminalInstance !== null) {
      terminalInstance.dispose();
      terminalInstance = null;
      fitAddon = null;
    }

    const createdTerminal = new Terminal({
      convertEol: false,
      cursorBlink: true,
      fontFamily: "ui-monospace, SFMono-Regular, Menlo, Consolas, monospace",
      fontSize: 13,
      scrollback: 5_000,
      theme: {
        background: "#0f172a",
        foreground: "#e2e8f0",
        cursor: "#93c5fd",
      },
    });
    const createdFitAddon = new FitAddon();

    createdTerminal.loadAddon(createdFitAddon);
    createdTerminal.open(terminalHostRef);
    createdFitAddon.fit();
    createdTerminal.onData((typedData) => {
      if (activeSocket === null || activeSocket.readyState !== WebSocket.OPEN) {
        return;
      }

      activeSocket.send(
        JSON.stringify({
          type: "input",
          data: typedData,
        }),
      );
    });

    terminalInstance = createdTerminal;
    fitAddon = createdFitAddon;
    flushPendingTerminalOutput();
  }

  function writeTerminalOutput(outputChunk: string): void {
    if (terminalInstance === null) {
      pendingTerminalOutputChunks.push(outputChunk);
      return;
    }

    terminalInstance.write(outputChunk);
  }

  function flushPendingTerminalOutput(): void {
    if (terminalInstance === null || pendingTerminalOutputChunks.length === 0) {
      return;
    }

    for (const pendingOutputChunk of pendingTerminalOutputChunks) {
      terminalInstance.write(pendingOutputChunk);
    }
    pendingTerminalOutputChunks = [];
  }

  function focusTerminal(): void {
    terminalInstance?.focus();
  }

  function sendResize(dimensions: TerminalDimensions): void {
    if (activeSocket === null || activeSocket.readyState !== WebSocket.OPEN) {
      return;
    }

    activeSocket.send(
      JSON.stringify({
        type: "resize",
        rows: dimensions.rows,
        cols: dimensions.cols,
      }),
    );
  }

  function fitAndResizeTerminal(): void {
    if (fitAddon === null || terminalInstance === null) {
      return;
    }

    fitAddon.fit();
    const terminalDimensions = fitAddon.proposeDimensions();
    if (terminalDimensions !== undefined) {
      sendResize(terminalDimensions);
    }
  }

  function getMinimumTerminalHeightPx(): number {
    return isPhoneViewport()
      ? PHONE_MIN_TERMINAL_HEIGHT
      : DESKTOP_MIN_TERMINAL_HEIGHT;
  }

  function getMaxTerminalHeightPx(): number {
    const minimumTerminalHeightPx = getMinimumTerminalHeightPx();
    if (terminalContainerRef === undefined) {
      return Math.max(
        minimumTerminalHeightPx,
        Math.floor(window.innerHeight * 0.8),
      );
    }

    const controlsHeightPx = terminalControlsRef?.offsetHeight ?? 0;
    const resizeHandleHeightPx = terminalResizeHandleRef?.offsetHeight ?? 0;
    const rowGapValue = window.getComputedStyle(terminalContainerRef).rowGap;
    const rowGapPx = Number.parseFloat(rowGapValue);
    const safeRowGapPx = Number.isFinite(rowGapPx) ? rowGapPx : 0;
    const reservedInsideContainerPx =
      controlsHeightPx + resizeHandleHeightPx + safeRowGapPx * 2;
    const sessionMetaHeightPx =
      terminalSessionMetaRef !== undefined
        ? terminalSessionMetaRef.offsetHeight + 8
        : 0;
    const parentHeightPx =
      terminalContainerRef.parentElement?.clientHeight ?? window.innerHeight;

    return Math.max(
      minimumTerminalHeightPx,
      parentHeightPx - sessionMetaHeightPx - reservedInsideContainerPx,
    );
  }

  function clampTerminalHeight(heightPx: number): number {
    return Math.max(
      getMinimumTerminalHeightPx(),
      Math.min(getMaxTerminalHeightPx(), heightPx),
    );
  }

  function ensureTerminalHeight(): void {
    if (terminalHeightPx() !== null) {
      return;
    }

    const initialRatio = isPhoneViewport()
      ? PHONE_INITIAL_HEIGHT_RATIO
      : DESKTOP_INITIAL_HEIGHT_RATIO;
    setTerminalHeightPx(
      clampTerminalHeight(Math.floor(getMaxTerminalHeightPx() * initialRatio)),
    );
  }

  function resizeTerminalHeight(deltaPx: number): void {
    ensureTerminalHeight();
    const currentHeightPx = terminalHeightPx();
    if (currentHeightPx === null) {
      return;
    }

    setTerminalHeightPx(clampTerminalHeight(currentHeightPx + deltaPx));
    window.requestAnimationFrame(() => {
      fitAndResizeTerminal();
    });
  }

  function resetTerminalHeight(): void {
    setTerminalHeightPx(null);
    ensureTerminalHeight();
    window.requestAnimationFrame(() => {
      fitAndResizeTerminal();
    });
  }

  function handleTerminalResizeMouseDown(mouseEvent: MouseEvent): void {
    mouseEvent.preventDefault();
    ensureTerminalHeight();

    const currentHeightPx = terminalHeightPx();
    if (currentHeightPx === null) {
      return;
    }

    isResizingTerminal = true;
    terminalDragStartY = mouseEvent.clientY;
    terminalDragStartHeightPx = currentHeightPx;
    document.body.style.cursor = "row-resize";
    document.body.style.userSelect = "none";
    window.addEventListener("mousemove", handleTerminalResizeMouseMove);
    window.addEventListener("mouseup", handleTerminalResizeMouseUp);
  }

  function handleTerminalResizeMouseMove(mouseEvent: MouseEvent): void {
    if (!isResizingTerminal) {
      return;
    }

    const deltaPx = mouseEvent.clientY - terminalDragStartY;
    setTerminalHeightPx(
      clampTerminalHeight(terminalDragStartHeightPx + deltaPx),
    );
    window.requestAnimationFrame(() => {
      fitAndResizeTerminal();
    });
  }

  function handleTerminalResizeMouseUp(): void {
    stopTerminalResizeDrag();
  }

  function handleServerMessage(payload: string): void {
    const serverMessage = parseTerminalServerMessage(payload);
    if (serverMessage === null) {
      return;
    }

    if (serverMessage.type === "output") {
      writeTerminalOutput(serverMessage.data);
      return;
    }

    if (serverMessage.type === "exit") {
      writeTerminalOutput(
        `\r\n\r\n[terminal exited with code ${serverMessage.code}]\r\n`,
      );
      setIsConnected(false);
      setActiveSessionId(null);
      return;
    }

    if (serverMessage.type === "error") {
      writeTerminalOutput(`\r\n[error] ${serverMessage.message}\r\n`);
      setConnectionError(serverMessage.message);
    }
  }

  async function connect(): Promise<void> {
    const contextId = props.contextId;
    if (contextId === null || isConnecting() || isConnected()) {
      return;
    }

    setIsConnecting(true);
    setConnectionError(null);

    try {
      const connectResponse = await terminalApi.connect(contextId);
      if (activeContextId !== contextId) {
        return;
      }

      setActiveSessionId(connectResponse.sessionId);
      await nextAnimationFrame();
      await nextAnimationFrame();
      ensureTerminalInitialized();

      if (terminalInstance === null) {
        throw new Error("Terminal UI could not be initialized");
      }

      terminalInstance.reset();
      terminalInstance.writeln(
        `[connected to ${contextId} in ${new Date().toLocaleTimeString()}]`,
      );

      attachSocket(contextId, connectResponse);
    } catch (error) {
      if (activeContextId !== contextId) {
        return;
      }

      setIsConnecting(false);
      setIsConnected(false);
      setActiveSessionId(null);
      setConnectionError(
        error instanceof Error ? error.message : "Terminal connection failed",
      );
    }
  }

  function attachSocket(
    contextId: string,
    connectResponse: TerminalConnectResponse,
  ): void {
    const socket = new WebSocket(
      buildTerminalWebSocketUrl(connectResponse, window.location),
    );
    activeSocket = socket;

    socket.onopen = () => {
      if (activeContextId !== contextId) {
        socket.close();
        return;
      }

      setIsConnecting(false);
      setIsConnected(true);
      window.requestAnimationFrame(() => {
        ensureTerminalInitialized();
        ensureTerminalHeight();
        fitAndResizeTerminal();
        focusTerminal();
      });
    };

    socket.onmessage = (messageEvent) => {
      if (activeContextId !== contextId) {
        return;
      }

      handleServerMessage(String(messageEvent.data));
    };

    socket.onerror = () => {
      if (activeContextId !== contextId) {
        return;
      }

      setConnectionError("Terminal WebSocket error");
    };

    socket.onclose = () => {
      if (activeSocket === socket) {
        activeSocket = null;
      }

      if (activeContextId !== contextId) {
        return;
      }

      setIsConnecting(false);
      setIsConnected(false);
      setActiveSessionId(null);
    };
  }

  async function tryResumeExistingSession(contextId: string): Promise<void> {
    if (isConnecting() || isConnected() || isCheckingStatus()) {
      return;
    }

    setIsCheckingStatus(true);
    try {
      const status = await terminalApi.fetchStatus(contextId);
      if (activeContextId !== contextId || !status.hasSession) {
        return;
      }

      await connect();
    } catch {
      // Ignore background status failures to preserve reconnect behavior.
    } finally {
      if (activeContextId === contextId) {
        setIsCheckingStatus(false);
      }
    }
  }

  async function disconnect(): Promise<void> {
    const contextId = props.contextId;
    if (contextId === null || isConnecting()) {
      return;
    }

    try {
      await terminalApi.disconnect(contextId);
    } catch {
      // Ignore network errors; local terminal resources still need cleanup.
    } finally {
      disposeTerminalResources();
      setConnectionError(null);
    }
  }

  onMount(() => {
    const handleWindowResize = (): void => {
      setIsPhoneViewport(detectPhoneViewport());
      const currentHeightPx = terminalHeightPx();
      if (currentHeightPx !== null) {
        setTerminalHeightPx(clampTerminalHeight(currentHeightPx));
      }
      window.requestAnimationFrame(() => {
        fitAndResizeTerminal();
      });
    };

    handleWindowResize();
    window.addEventListener("resize", handleWindowResize);

    onCleanup(() => {
      window.removeEventListener("resize", handleWindowResize);
    });
  });

  createEffect(() => {
    const contextId = props.contextId;
    if (contextId === lastObservedContextId) {
      return;
    }

    lastObservedContextId = contextId;
    activeContextId = contextId;
    disposeTerminalResources();
    setConnectionError(null);

    if (contextId !== null) {
      void tryResumeExistingSession(contextId);
    }
  });

  createEffect(() => {
    terminalHeightPx();
    if (!(isConnected() || isConnecting())) {
      return;
    }

    ensureTerminalInitialized();

    if (!isConnected()) {
      return;
    }

    window.requestAnimationFrame(() => {
      fitAndResizeTerminal();
    });
  });

  onCleanup(() => {
    stopTerminalResizeDrag();
    disposeTerminalResources();
  });

  return (
    <section class="mx-auto flex h-full max-w-7xl flex-col gap-6 px-4 py-6 sm:px-6">
      <ScreenHeader title="Terminal" />

      <Show
        when={props.contextId !== null}
        fallback={
          <div class="flex min-h-[420px] items-center justify-center rounded-2xl border border-border-default bg-bg-secondary px-6 text-center text-sm text-text-secondary">
            Open a project tab to start a terminal session.
          </div>
        }
      >
        <Show
          when={isConnected() || isConnecting()}
          fallback={
            <div class="flex min-h-[420px] flex-1 items-center justify-center rounded-2xl border border-border-default bg-bg-secondary p-6 text-center">
              <div>
                <ToolbarIconButton
                  label="Connect terminal"
                  onClick={() => void connect()}
                >
                  <svg
                    width="16"
                    height="16"
                    viewBox="0 0 16 16"
                    fill="none"
                    aria-hidden="true"
                  >
                    <path
                      d="M6 2.75h4v4h2.25a1 1 0 0 1 1 1v1.5a1 1 0 0 1-1 1H10v3.25H6V10.25H3.75a1 1 0 0 1-1-1v-1.5a1 1 0 0 1 1-1H6v-4Z"
                      stroke="currentColor"
                      stroke-width="1.5"
                      stroke-linejoin="round"
                    />
                  </svg>
                </ToolbarIconButton>
                <Show when={connectionError() !== null}>
                  <p class="mt-4 text-sm text-danger-fg">{connectionError()}</p>
                </Show>
              </div>
            </div>
          }
        >
          <div class="flex min-h-0 flex-1 flex-col gap-2 rounded-2xl border border-border-default bg-bg-secondary p-3">
            <div
              ref={(element) => {
                terminalContainerRef = element;
              }}
              class="flex h-full min-h-0 w-full flex-col gap-2"
            >
              <div
                ref={(element) => {
                  terminalControlsRef = element;
                }}
                class="flex flex-wrap items-center justify-between gap-2"
              >
                <div class="flex flex-wrap items-center gap-2">
                  <span class="rounded-full border border-border-default bg-bg-primary px-3 py-1.5 text-xs font-medium text-text-secondary">
                    {isConnected()
                      ? "Connected"
                      : isConnecting()
                        ? "Connecting"
                        : isCheckingStatus()
                          ? "Checking"
                          : "Disconnected"}
                  </span>
                  <ToolbarIconButton
                    label="Send Ctrl+C"
                    disabled={!isConnected()}
                    onClick={() => {
                      if (
                        activeSocket !== null &&
                        activeSocket.readyState === WebSocket.OPEN
                      ) {
                        activeSocket.send(
                          JSON.stringify({
                            type: "input",
                            data: "\u0003",
                          }),
                        );
                      }
                    }}
                  >
                    <svg
                      width="14"
                      height="14"
                      viewBox="0 0 16 16"
                      fill="none"
                      aria-hidden="true"
                    >
                      <path
                        d="M8 3v10M3 8h10"
                        stroke="currentColor"
                        stroke-width="1.8"
                        stroke-linecap="round"
                      />
                      <path
                        d="M4 4l8 8"
                        stroke="currentColor"
                        stroke-width="1.8"
                        stroke-linecap="round"
                      />
                    </svg>
                  </ToolbarIconButton>
                  <ToolbarIconButton
                    label="Disconnect terminal"
                    disabled={isConnecting()}
                    onClick={() => void disconnect()}
                  >
                    <svg
                      width="14"
                      height="14"
                      viewBox="0 0 16 16"
                      fill="none"
                      aria-hidden="true"
                    >
                      <path
                        d="M6 4.5A4.5 4.5 0 1 0 10 12"
                        stroke="currentColor"
                        stroke-width="1.8"
                        stroke-linecap="round"
                      />
                      <path
                        d="M10 3.5h3v3M13 3.5l-4 4"
                        stroke="currentColor"
                        stroke-width="1.8"
                        stroke-linecap="round"
                        stroke-linejoin="round"
                      />
                    </svg>
                  </ToolbarIconButton>
                </div>

                <div class="flex flex-wrap items-center gap-2">
                  <ToolbarIconButton
                    label="Increase terminal height"
                    onClick={() => resizeTerminalHeight(120)}
                  >
                    <svg
                      width="14"
                      height="14"
                      viewBox="0 0 16 16"
                      fill="none"
                      aria-hidden="true"
                    >
                      <path
                        d="M8 3v10M3 8h10"
                        stroke="currentColor"
                        stroke-width="2"
                        stroke-linecap="round"
                      />
                    </svg>
                  </ToolbarIconButton>
                  <ToolbarIconButton
                    label="Decrease terminal height"
                    onClick={() => resizeTerminalHeight(-120)}
                  >
                    <svg
                      width="14"
                      height="14"
                      viewBox="0 0 16 16"
                      fill="none"
                      aria-hidden="true"
                    >
                      <path
                        d="M3 8h10"
                        stroke="currentColor"
                        stroke-width="2"
                        stroke-linecap="round"
                      />
                    </svg>
                  </ToolbarIconButton>
                  <ToolbarIconButton
                    label="Reset terminal height"
                    onClick={resetTerminalHeight}
                  >
                    <svg
                      width="14"
                      height="14"
                      viewBox="0 0 16 16"
                      fill="none"
                      aria-hidden="true"
                    >
                      <path
                        d="M3 8a5 5 0 1 0 1.5-3.6M3 3v3h3"
                        stroke="currentColor"
                        stroke-width="1.8"
                        stroke-linecap="round"
                        stroke-linejoin="round"
                      />
                    </svg>
                  </ToolbarIconButton>
                </div>
              </div>

              <Show when={connectionError() !== null}>
                <p class="text-sm text-danger-fg">{connectionError()}</p>
              </Show>

              <div
                class="min-h-0 w-full shrink-0 overflow-hidden rounded-md border border-border-default bg-slate-900"
                style={{
                  height: `${terminalHeightPx() ?? (isPhoneViewport() ? Math.floor(window.innerHeight * PHONE_TERMINAL_HEIGHT_RATIO) : DEFAULT_TERMINAL_HEIGHT)}px`,
                }}
                onClick={focusTerminal}
                onKeyDown={focusTerminal}
                role="button"
                tabindex="0"
              >
                <div
                  ref={(element) => {
                    terminalHostRef = element;
                    ensureTerminalInitialized();
                  }}
                  class="terminal-host h-full w-full"
                />
              </div>

              <div
                ref={(element) => {
                  terminalResizeHandleRef = element;
                }}
                class="group flex h-5 cursor-row-resize items-center justify-center rounded-sm transition-colors hover:bg-accent-muted/40"
                role="separator"
                aria-orientation="horizontal"
                aria-label="Resize terminal height"
                onMouseDown={handleTerminalResizeMouseDown}
              >
                <div class="h-0.5 w-8 rounded-full bg-border-default transition-colors group-hover:bg-accent-emphasis" />
              </div>
            </div>

            <Show when={activeSessionId() !== null}>
              <p
                ref={(element) => {
                  terminalSessionMetaRef = element;
                }}
                class="text-xs text-text-tertiary"
              >
                session: {activeSessionId()}
              </p>
            </Show>
          </div>
        </Show>
      </Show>
    </section>
  );
}
