// client/src/features/commits/CommitsScreen.tsx
import {
  createEffect,
  createSignal,
  For,
  type JSX,
  Show,
  untrack,
} from "solid-js";
import { createCommitApiClient } from "../../../../client-shared/src/api/commits";
import type { DiffFile } from "../../../../client-shared/src/contracts/diff";
import type { CommitDetail, CommitInfo } from "../../../../src/types/commit";
import {
  collectCommitDiffPreviewLines,
  formatCommitRelativeDate,
  formatCommitStatusLabel,
  getCommitHeadline,
  getCommitListSummary,
} from "./presentation";
import { applyCommitSearchDraft, buildAppliedCommitSearchQuery } from "./state";

export interface CommitsScreenProps {
  readonly apiBaseUrl: string;
  readonly contextId: string | null;
  readonly isGitRepo: boolean;
}

const COMMIT_PAGE_SIZE = 50;

function getCommitFileStatusClass(status: string): string {
  if (status === "Added") {
    return "border border-success-emphasis/30 bg-success-muted/15 text-success-fg";
  }

  if (status === "Deleted") {
    return "border border-danger-emphasis/30 bg-danger-muted/15 text-danger-fg";
  }

  if (status === "Modified") {
    return "border border-attention-emphasis/30 bg-attention-muted/15 text-attention-fg";
  }

  return "border border-accent-emphasis/30 bg-accent-muted/15 text-accent-fg";
}

export function CommitsScreen(props: CommitsScreenProps): JSX.Element {
  const commitApi = createCommitApiClient({
    apiBaseUrl: props.apiBaseUrl,
  });

  const [commits, setCommits] = createSignal<readonly CommitInfo[]>([]);
  const [isLoading, setIsLoading] = createSignal(false);
  const [isLoadingMore, setIsLoadingMore] = createSignal(false);
  const [errorMessage, setErrorMessage] = createSignal<string | null>(null);
  const [hasMore, setHasMore] = createSignal(false);
  const [offset, setOffset] = createSignal(0);
  const [searchDraftQuery, setSearchDraftQuery] = createSignal("");
  const [appliedSearchQuery, setAppliedSearchQuery] = createSignal("");

  const [expandedHash, setExpandedHash] = createSignal<string | null>(null);
  const [commitDetail, setCommitDetail] = createSignal<CommitDetail | null>(
    null,
  );
  const [isDetailLoading, setIsDetailLoading] = createSignal(false);
  const [detailError, setDetailError] = createSignal<string | null>(null);

  const [expandedFilePath, setExpandedFilePath] = createSignal<string | null>(
    null,
  );
  const [fileDiffPreviewLines, setFileDiffPreviewLines] = createSignal<
    readonly string[]
  >([]);
  const [isFileDiffLoading, setIsFileDiffLoading] = createSignal(false);
  const [fileDiffError, setFileDiffError] = createSignal<string | null>(null);

  let activeContextId: string | null = null;
  let diffCache = new Map<string, readonly DiffFile[]>();
  let lastDetailRequestId = 0;
  let lastDiffRequestId = 0;

  async function loadCommits(append: boolean): Promise<void> {
    const contextId = props.contextId;
    if (contextId === null || !props.isGitRepo) {
      setCommits([]);
      setHasMore(false);
      setOffset(0);
      return;
    }

    activeContextId = contextId;
    if (append) {
      setIsLoadingMore(true);
    } else {
      setIsLoading(true);
    }
    setErrorMessage(null);

    try {
      const response = await commitApi.fetchCommitLog(contextId, {
        limit: COMMIT_PAGE_SIZE,
        offset: append ? offset() : 0,
        search: untrack(() =>
          buildAppliedCommitSearchQuery(appliedSearchQuery()),
        ),
      });
      if (activeContextId !== contextId) {
        return;
      }

      setCommits((currentCommits) =>
        append ? [...currentCommits, ...response.commits] : response.commits,
      );
      setHasMore(response.pagination.hasMore);
      setOffset(response.pagination.offset + response.pagination.limit);
    } catch (error) {
      if (activeContextId !== contextId) {
        return;
      }
      setErrorMessage(
        error instanceof Error ? error.message : "Failed to load commits",
      );
    } finally {
      if (activeContextId === contextId) {
        setIsLoading(false);
        setIsLoadingMore(false);
      }
    }
  }

  function resetExpandedState(): void {
    setExpandedHash(null);
    setCommitDetail(null);
    setDetailError(null);
    setIsDetailLoading(false);
    setExpandedFilePath(null);
    setFileDiffPreviewLines([]);
    setFileDiffError(null);
    setIsFileDiffLoading(false);
  }

  createEffect(() => {
    const contextId = props.contextId;
    const isGitRepo = props.isGitRepo;

    activeContextId = contextId;
    diffCache = new Map();
    lastDetailRequestId += 1;
    lastDiffRequestId += 1;
    setCommits([]);
    setHasMore(false);
    setOffset(0);
    resetExpandedState();

    if (contextId === null || !isGitRepo) {
      setIsLoading(false);
      setIsLoadingMore(false);
      setErrorMessage(null);
      return;
    }

    void loadCommits(false);
  });

  async function handleSearch(): Promise<void> {
    setAppliedSearchQuery(applyCommitSearchDraft(searchDraftQuery()));
    setOffset(0);
    resetExpandedState();
    await loadCommits(false);
  }

  async function toggleCommit(hash: string): Promise<void> {
    if (props.contextId === null) {
      return;
    }

    if (expandedHash() === hash) {
      resetExpandedState();
      return;
    }

    setExpandedHash(hash);
    setCommitDetail(null);
    setDetailError(null);
    setExpandedFilePath(null);
    setFileDiffPreviewLines([]);
    setFileDiffError(null);
    setIsDetailLoading(true);
    const requestId = lastDetailRequestId + 1;
    lastDetailRequestId = requestId;
    const contextId = props.contextId;

    try {
      const detail = await commitApi.fetchCommitDetail(contextId, hash);
      if (
        requestId !== lastDetailRequestId ||
        props.contextId !== contextId ||
        expandedHash() !== hash
      ) {
        return;
      }
      setCommitDetail(detail);
    } catch (error) {
      if (requestId !== lastDetailRequestId || props.contextId !== contextId) {
        return;
      }
      setDetailError(
        error instanceof Error ? error.message : "Failed to load commit detail",
      );
    } finally {
      if (requestId === lastDetailRequestId && props.contextId === contextId) {
        setIsDetailLoading(false);
      }
    }
  }

  async function toggleFileDiff(filePath: string): Promise<void> {
    if (props.contextId === null) {
      return;
    }

    if (expandedFilePath() === filePath) {
      setExpandedFilePath(null);
      setFileDiffPreviewLines([]);
      setFileDiffError(null);
      return;
    }

    setExpandedFilePath(filePath);
    setFileDiffPreviewLines([]);
    setFileDiffError(null);

    const currentHash = expandedHash();
    if (currentHash === null) {
      return;
    }

    const cachedDiffFiles = diffCache.get(currentHash);
    if (cachedDiffFiles !== undefined) {
      setFileDiffPreviewLines(
        collectCommitDiffPreviewLines(
          cachedDiffFiles.filter((diffFile) => diffFile.path === filePath),
        ),
      );
      return;
    }

    setIsFileDiffLoading(true);
    const requestId = lastDiffRequestId + 1;
    lastDiffRequestId = requestId;
    const contextId = props.contextId;
    try {
      const diffFiles = await commitApi.fetchCommitDiff(contextId, currentHash);
      if (
        requestId !== lastDiffRequestId ||
        props.contextId !== contextId ||
        expandedHash() !== currentHash ||
        expandedFilePath() !== filePath
      ) {
        return;
      }
      diffCache.set(currentHash, diffFiles);
      setFileDiffPreviewLines(
        collectCommitDiffPreviewLines(
          diffFiles.filter((diffFile) => diffFile.path === filePath),
        ),
      );
    } catch (error) {
      if (requestId !== lastDiffRequestId || props.contextId !== contextId) {
        return;
      }
      setFileDiffError(
        error instanceof Error ? error.message : "Failed to load file diff",
      );
    } finally {
      if (requestId === lastDiffRequestId && props.contextId === contextId) {
        setIsFileDiffLoading(false);
      }
    }
  }

  return (
    <section class="flex min-h-0 flex-1 flex-col gap-4">
      <header class="grid gap-3 md:grid-cols-3">
        <div class="rounded-2xl border border-border-default bg-bg-secondary p-5 shadow-lg shadow-black/15 md:col-span-2">
          <p class="text-xs font-semibold uppercase tracking-[0.24em] text-accent-fg">
            Commits
          </p>
          <h2 class="mt-2 text-2xl font-semibold text-text-primary">
            Commit History
          </h2>
          <p class="mt-2 text-sm leading-6 text-text-secondary">
            Browse recent history, inspect a commit’s changed files, and expand
            per-file previews from a card-based log instead of the migration
            placeholder list.
          </p>
        </div>
        <div class="rounded-2xl border border-border-default bg-bg-secondary p-5">
          <p class="text-xs uppercase tracking-[0.22em] text-text-tertiary">
            Summary
          </p>
          <p class="mt-3 text-lg font-semibold text-text-primary">
            {getCommitListSummary(commits(), hasMore())}
          </p>
          <p class="mt-2 text-sm text-text-secondary">
            {props.isGitRepo
              ? "Search and expand commits without leaving the workspace."
              : "Commit history is unavailable for non-Git workspaces."}
          </p>
        </div>
      </header>

      <Show
        when={props.isGitRepo}
        fallback={
          <div class="flex min-h-[420px] items-center justify-center rounded-2xl border border-border-default bg-bg-secondary px-6 text-center text-sm text-text-secondary">
            The active workspace is not a Git repository, so commit history is
            unavailable.
          </div>
        }
      >
        <div class="flex min-h-0 flex-1 flex-col overflow-hidden rounded-2xl border border-border-default bg-bg-secondary">
          <div class="border-b border-border-default p-4">
            <div class="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between">
              <div class="flex flex-wrap items-center gap-3 text-sm text-text-secondary">
                <span class="rounded-full border border-border-default bg-bg-primary px-3 py-1">
                  {commits().length} loaded
                </span>
                <Show when={hasMore()}>
                  <span class="rounded-full border border-border-default bg-bg-primary px-3 py-1">
                    more available
                  </span>
                </Show>
              </div>

              <div class="flex flex-col gap-3 sm:flex-row">
                <input
                  value={searchDraftQuery()}
                  class="min-w-[240px] rounded-md border border-border-default bg-bg-primary px-3 py-2 text-sm text-text-primary outline-none transition focus:border-accent-emphasis"
                  placeholder="Search commits..."
                  onInput={(event) =>
                    setSearchDraftQuery(event.currentTarget.value)
                  }
                  onKeyDown={(event) => {
                    if (event.key === "Enter") {
                      event.preventDefault();
                      void handleSearch();
                    }
                  }}
                />
                <div class="flex gap-2">
                  <button
                    type="button"
                    class="rounded-md bg-accent-emphasis px-4 py-2 text-sm font-semibold text-text-on-emphasis transition hover:bg-accent-fg"
                    onClick={() => void handleSearch()}
                  >
                    Search
                  </button>
                  <button
                    type="button"
                    class="rounded-md border border-border-default bg-bg-primary px-4 py-2 text-sm font-medium text-text-primary transition hover:bg-bg-hover"
                    onClick={() => void loadCommits(false)}
                  >
                    Refresh
                  </button>
                </div>
              </div>
            </div>
          </div>

          <div class="min-h-0 flex-1 overflow-y-auto p-4">
            <Show when={isLoading()}>
              <div class="flex min-h-[240px] items-center justify-center text-sm text-text-secondary">
                Loading commits...
              </div>
            </Show>

            <Show when={errorMessage() !== null}>
              <div class="mb-4 rounded-xl border border-danger-emphasis/30 bg-danger-muted/10 p-4 text-sm text-danger-fg">
                {errorMessage()}
              </div>
            </Show>

            <Show
              when={
                !isLoading() &&
                errorMessage() === null &&
                commits().length === 0
              }
            >
              <div class="flex min-h-[260px] items-center justify-center rounded-xl border border-dashed border-border-default bg-bg-primary/40 px-6 py-10 text-center text-sm text-text-secondary">
                {appliedSearchQuery().trim().length > 0
                  ? "No commits match the current search."
                  : "No commits found for this repository."}
              </div>
            </Show>

            <div class="space-y-3">
              <For each={commits()}>
                {(commit) => {
                  const isExpanded = () => expandedHash() === commit.hash;
                  return (
                    <article class="overflow-hidden rounded-xl border border-border-default bg-bg-primary">
                      <button
                        type="button"
                        class="flex w-full items-center gap-3 px-4 py-4 text-left transition hover:bg-bg-hover"
                        onClick={() => void toggleCommit(commit.hash)}
                      >
                        <span class="shrink-0 text-text-tertiary">
                          {isExpanded() ? "▾" : "▸"}
                        </span>
                        <span class="rounded bg-bg-tertiary px-2 py-1 font-mono text-[10px] font-bold text-accent-fg">
                          {commit.shortHash}
                        </span>
                        <div class="min-w-0 flex-1">
                          <p class="truncate text-sm font-medium text-text-primary">
                            {getCommitHeadline(commit.message)}
                          </p>
                          <div class="mt-1 flex flex-wrap items-center gap-3 text-xs text-text-tertiary">
                            <span>{commit.author.name}</span>
                            <span>{formatCommitRelativeDate(commit.date)}</span>
                          </div>
                        </div>
                      </button>

                      <Show when={isExpanded()}>
                        <div class="border-t border-border-default bg-bg-secondary p-4">
                          <Show when={isDetailLoading()}>
                            <div class="rounded-xl border border-border-default bg-bg-primary px-4 py-3 text-sm text-text-secondary">
                              Loading commit detail...
                            </div>
                          </Show>
                          <Show when={detailError() !== null}>
                            <div class="rounded-xl border border-danger-emphasis/30 bg-danger-muted/10 px-4 py-3 text-sm text-danger-fg">
                              {detailError()}
                            </div>
                          </Show>
                          <Show
                            when={
                              !isDetailLoading() &&
                              detailError() === null &&
                              commitDetail() !== null
                            }
                          >
                            <div class="space-y-4">
                              <div class="grid gap-3 lg:grid-cols-[minmax(0,1fr)_240px]">
                                <div class="rounded-xl border border-border-default bg-bg-primary p-4">
                                  <p class="text-xs uppercase tracking-wide text-text-tertiary">
                                    Commit message
                                  </p>
                                  <p class="mt-2 whitespace-pre-wrap text-sm leading-6 text-text-primary">
                                    {commitDetail()!.message}
                                  </p>
                                  <Show
                                    when={
                                      commitDetail()!.body.trim().length > 0
                                    }
                                  >
                                    <pre class="mt-4 whitespace-pre-wrap rounded-lg border border-border-default bg-bg-secondary p-3 text-xs leading-6 text-text-secondary">
                                      {commitDetail()!.body}
                                    </pre>
                                  </Show>
                                </div>
                                <div class="space-y-3">
                                  <div class="rounded-xl border border-border-default bg-bg-primary p-4">
                                    <p class="text-xs uppercase tracking-wide text-text-tertiary">
                                      Full hash
                                    </p>
                                    <p class="mt-2 break-all font-mono text-xs text-text-primary">
                                      {commitDetail()!.hash}
                                    </p>
                                  </div>
                                  <div class="rounded-xl border border-border-default bg-bg-primary p-4">
                                    <p class="text-xs uppercase tracking-wide text-text-tertiary">
                                      Stats
                                    </p>
                                    <div class="mt-3 flex flex-wrap gap-2 text-xs">
                                      <span class="rounded-full border border-border-default bg-bg-secondary px-2 py-1 text-text-secondary">
                                        {commitDetail()!.stats.filesChanged}{" "}
                                        files
                                      </span>
                                      <span class="rounded-full border border-success-emphasis/30 bg-success-muted/15 px-2 py-1 text-success-fg">
                                        +{commitDetail()!.stats.additions}
                                      </span>
                                      <span class="rounded-full border border-danger-emphasis/30 bg-danger-muted/15 px-2 py-1 text-danger-fg">
                                        -{commitDetail()!.stats.deletions}
                                      </span>
                                    </div>
                                  </div>
                                </div>
                              </div>

                              <Show
                                when={commitDetail()!.files.length > 0}
                                fallback={
                                  <div class="rounded-xl border border-dashed border-border-default bg-bg-primary/40 px-4 py-6 text-sm text-text-secondary">
                                    No changed files are recorded.
                                  </div>
                                }
                              >
                                <div class="space-y-3">
                                  <For each={commitDetail()!.files}>
                                    {(file) => {
                                      const statusLabel =
                                        formatCommitStatusLabel(file.status);
                                      return (
                                        <article class="overflow-hidden rounded-xl border border-border-default bg-bg-primary">
                                          <button
                                            type="button"
                                            class="flex w-full items-start gap-3 px-4 py-4 text-left transition hover:bg-bg-hover"
                                            onClick={() =>
                                              void toggleFileDiff(file.path)
                                            }
                                          >
                                            <span class="shrink-0 text-text-tertiary">
                                              {expandedFilePath() === file.path
                                                ? "▾"
                                                : "▸"}
                                            </span>
                                            <div class="min-w-0 flex-1">
                                              <div class="flex flex-wrap items-center gap-2">
                                                <p class="truncate text-sm font-medium text-text-primary">
                                                  {file.path}
                                                </p>
                                                <span
                                                  class={`rounded-full px-2 py-1 text-[10px] font-semibold uppercase tracking-wide ${getCommitFileStatusClass(
                                                    statusLabel,
                                                  )}`}
                                                >
                                                  {statusLabel}
                                                </span>
                                              </div>
                                              <Show
                                                when={
                                                  file.oldPath !== undefined
                                                }
                                              >
                                                <p class="mt-1 text-xs text-text-secondary">
                                                  from {file.oldPath}
                                                </p>
                                              </Show>
                                              <div class="mt-2 flex gap-2 text-xs">
                                                <span class="rounded-full border border-success-emphasis/30 bg-success-muted/15 px-2 py-1 text-success-fg">
                                                  +{file.additions}
                                                </span>
                                                <span class="rounded-full border border-danger-emphasis/30 bg-danger-muted/15 px-2 py-1 text-danger-fg">
                                                  -{file.deletions}
                                                </span>
                                              </div>
                                            </div>
                                          </button>

                                          <Show
                                            when={
                                              expandedFilePath() === file.path
                                            }
                                          >
                                            <div class="border-t border-border-default bg-bg-secondary p-4">
                                              <Show when={isFileDiffLoading()}>
                                                <div class="rounded-lg border border-border-default bg-bg-primary px-4 py-3 text-sm text-text-secondary">
                                                  Loading diff preview...
                                                </div>
                                              </Show>
                                              <Show
                                                when={fileDiffError() !== null}
                                              >
                                                <div class="rounded-lg border border-danger-emphasis/30 bg-danger-muted/10 px-4 py-3 text-sm text-danger-fg">
                                                  {fileDiffError()}
                                                </div>
                                              </Show>
                                              <Show
                                                when={
                                                  !isFileDiffLoading() &&
                                                  fileDiffError() === null &&
                                                  fileDiffPreviewLines()
                                                    .length > 0
                                                }
                                                fallback={
                                                  <div class="rounded-lg border border-dashed border-border-default bg-bg-primary/40 px-4 py-6 text-sm text-text-secondary">
                                                    No diff preview is available
                                                    for this file.
                                                  </div>
                                                }
                                              >
                                                <pre class="overflow-x-auto rounded-lg border border-border-default bg-[#020817] px-4 py-4 font-mono text-[12px] leading-6 text-slate-100">
                                                  {fileDiffPreviewLines().join(
                                                    "\n",
                                                  )}
                                                </pre>
                                              </Show>
                                            </div>
                                          </Show>
                                        </article>
                                      );
                                    }}
                                  </For>
                                </div>
                              </Show>
                            </div>
                          </Show>
                        </div>
                      </Show>
                    </article>
                  );
                }}
              </For>
            </div>

            <Show when={hasMore()}>
              <div class="mt-4 flex justify-center">
                <button
                  type="button"
                  disabled={isLoadingMore()}
                  class="rounded-md border border-border-default bg-bg-primary px-4 py-2 text-sm font-medium text-text-primary transition hover:bg-bg-hover disabled:cursor-not-allowed disabled:opacity-50"
                  onClick={() => void loadCommits(true)}
                >
                  {isLoadingMore() ? "Loading..." : "Load more"}
                </button>
              </div>
            </Show>
          </div>
        </div>
      </Show>
    </section>
  );
}

// client/components/commits/CommitsScreen.svelte
<script lang="ts">
  import type {
    CommitInfo,
    CommitDetail,
    CommitLogResponse,
    CommitFileChange,
  } from "../../../src/types/commit";

  interface Props {
    contextId: string;
    onBack: () => void;
  }

  const { contextId, onBack }: Props = $props();

  /**
   * Commit list state
   */
  let commits = $state<CommitInfo[]>([]);
  let loading = $state(true);
  let loadingMore = $state(false);
  let error = $state<string | null>(null);
  let hasMore = $state(false);
  let offset = $state(0);
  const limit = 50;

  /**
   * Search state
   */
  let searchInput = $state("");
  let searchQuery = $state("");
  let searchTimeout = $state<ReturnType<typeof setTimeout> | null>(null);

  /**
   * Expanded commit detail state
   */
  let expandedHash = $state<string | null>(null);
  let commitDetail = $state<CommitDetail | null>(null);
  let loadingDetail = $state(false);
  let detailError = $state<string | null>(null);

  /**
   * Debounce search input
   */
  function handleSearchInput(value: string): void {
    searchInput = value;
    if (searchTimeout !== null) {
      clearTimeout(searchTimeout);
    }
    searchTimeout = setTimeout(() => {
      searchQuery = value;
      offset = 0;
      commits = [];
      void fetchCommits(false);
    }, 300);
  }

  /**
   * Fetch commits from the API
   */
  async function fetchCommits(append: boolean): Promise<void> {
    if (append) {
      loadingMore = true;
    } else {
      loading = true;
    }
    error = null;

    try {
      const params = new URLSearchParams();
      params.set("limit", limit.toString());
      params.set("offset", append ? offset.toString() : "0");
      if (searchQuery.trim().length > 0) {
        params.set("search", searchQuery.trim());
      }

      const resp = await fetch(
        `/api/ctx/${contextId}/commits?${params.toString()}`,
      );
      if (!resp.ok) {
        const errData = (await resp.json().catch(() => null)) as {
          error?: string;
        } | null;
        throw new Error(
          errData?.error ?? `Failed to load commits (${resp.status})`,
        );
      }

      const data = (await resp.json()) as CommitLogResponse;
      if (append) {
        commits = [...commits, ...data.commits];
      } else {
        commits = [...data.commits];
      }
      hasMore = data.pagination.hasMore;
      offset = data.pagination.offset + data.pagination.limit;
    } catch (e) {
      error = e instanceof Error ? e.message : "Failed to load commits";
    } finally {
      loading = false;
      loadingMore = false;
    }
  }

  /**
   * Load more commits (pagination)
   */
  function handleLoadMore(): void {
    if (loadingMore || !hasMore) return;
    void fetchCommits(true);
  }

  /**
   * Retry after error
   */
  function handleRetry(): void {
    offset = 0;
    commits = [];
    void fetchCommits(false);
  }

  /**
   * Toggle expanded commit detail
   */
  async function toggleCommit(hash: string): Promise<void> {
    if (expandedHash === hash) {
      expandedHash = null;
      commitDetail = null;
      detailError = null;
      return;
    }

    expandedHash = hash;
    commitDetail = null;
    detailError = null;
    loadingDetail = true;

    try {
      const resp = await fetch(`/api/ctx/${contextId}/commits/${hash}`);
      if (!resp.ok) {
        const errData = (await resp.json().catch(() => null)) as {
          error?: string;
        } | null;
        throw new Error(
          errData?.error ?? `Failed to load commit detail (${resp.status})`,
        );
      }
      commitDetail = (await resp.json()) as CommitDetail;
    } catch (e) {
      detailError =
        e instanceof Error ? e.message : "Failed to load commit detail";
    } finally {
      loadingDetail = false;
    }
  }

  /**
   * Format timestamp to relative date
   */
  function formatRelativeDate(timestamp: number): string {
    const date = new Date(timestamp);
    const now = new Date();
    const diff = now.getTime() - date.getTime();
    const days = Math.floor(diff / (1000 * 60 * 60 * 24));

    if (days === 0) {
      const hours = Math.floor(diff / (1000 * 60 * 60));
      if (hours === 0) {
        const minutes = Math.floor(diff / (1000 * 60));
        return minutes <= 1 ? "just now" : `${minutes} min ago`;
      }
      return hours === 1 ? "1 hour ago" : `${hours} hours ago`;
    }
    if (days === 1) return "yesterday";
    if (days < 7) return `${days} days ago`;
    if (days < 30) {
      const weeks = Math.floor(days / 7);
      return weeks === 1 ? "1 week ago" : `${weeks} weeks ago`;
    }
    return date.toLocaleDateString(undefined, {
      year: "numeric",
      month: "short",
      day: "numeric",
    });
  }

  /**
   * Get first line of commit message
   */
  function firstLine(message: string): string {
    const line = message.split("\n")[0];
    return line ?? message;
  }

  /**
   * Status label for file change
   */
  function statusLabel(status: CommitFileChange["status"]): string {
    switch (status) {
      case "A":
        return "Added";
      case "M":
        return "Modified";
      case "D":
        return "Deleted";
      case "R":
        return "Renamed";
      case "C":
        return "Copied";
      default:
        return status;
    }
  }

  /**
   * CSS class for file change status
   */
  function statusClass(status: CommitFileChange["status"]): string {
    switch (status) {
      case "A":
        return "text-success-fg";
      case "D":
        return "text-danger-fg";
      case "M":
        return "text-attention-fg";
      case "R":
        return "text-accent-fg";
      case "C":
        return "text-accent-fg";
      default:
        return "text-text-secondary";
    }
  }

  // Fetch commits on mount
  $effect(() => {
    void fetchCommits(false);
  });
</script>

<div class="flex flex-col h-full bg-bg-primary text-text-primary">
  <!-- Header -->
  <div
    class="flex items-center gap-3 px-4 py-3 border-b border-border-default bg-bg-secondary shrink-0"
  >
    <button
      type="button"
      class="px-2 py-1 text-sm rounded hover:bg-bg-tertiary transition-colors text-text-secondary"
      onclick={onBack}
      aria-label="Go back"
    >
      &lt;
    </button>
    <h2 class="text-lg font-semibold">Commit Log</h2>
  </div>

  <!-- Search -->
  <div class="px-4 py-3 border-b border-border-default shrink-0">
    <input
      type="text"
      class="w-full px-3 py-2 text-sm border border-border-default rounded bg-bg-primary text-text-primary placeholder-text-tertiary focus:outline-none focus:ring-2 focus:ring-accent-emphasis focus:border-transparent"
      placeholder="Search commits by message, author, or hash..."
      value={searchInput}
      oninput={(e) => handleSearchInput(e.currentTarget.value)}
      aria-label="Search commits"
    />
  </div>

  <!-- Commit List -->
  <div class="flex-1 overflow-y-auto">
    {#if loading}
      <!-- Loading State -->
      <div class="flex items-center justify-center p-8 text-text-secondary">
        <div class="flex flex-col items-center gap-2">
          <div
            class="w-6 h-6 border-2 border-border-default border-t-accent-emphasis rounded-full animate-spin"
          ></div>
          <p class="text-sm">Loading commits...</p>
        </div>
      </div>
    {:else if error !== null && commits.length === 0}
      <!-- Error State -->
      <div class="flex items-center justify-center p-8">
        <div class="flex flex-col items-center gap-3 text-center">
          <p class="text-sm text-danger-fg">{error}</p>
          <button
            type="button"
            class="px-4 py-2 text-sm bg-bg-tertiary text-text-primary border border-border-default rounded hover:bg-bg-hover transition-colors"
            onclick={handleRetry}
          >
            Retry
          </button>
        </div>
      </div>
    {:else if commits.length === 0}
      <!-- Empty State -->
      <div class="flex items-center justify-center p-8 text-text-secondary">
        <p class="text-sm">
          {searchQuery.trim().length > 0
            ? "No commits match your search"
            : "No commits found"}
        </p>
      </div>
    {:else}
      <!-- Commit Items -->
      {#each commits as commit (commit.hash)}
        {@const isExpanded = expandedHash === commit.hash}
        <div
          class="border-b border-border-default {isExpanded
            ? 'bg-bg-secondary'
            : ''}"
        >
          <!-- Commit Row -->
          <button
            type="button"
            class="w-full text-left px-4 py-3 hover:bg-bg-tertiary transition-colors flex flex-col gap-1"
            onclick={() => void toggleCommit(commit.hash)}
            aria-expanded={isExpanded}
          >
            <div class="flex items-center gap-2 text-xs text-text-secondary">
              <span class="font-mono text-accent-fg"
                >{commit.shortHash || commit.hash.slice(0, 7)}</span
              >
              <span>{formatRelativeDate(commit.date)}</span>
              <span class="ml-auto">{commit.author.name}</span>
            </div>
            <div class="text-sm text-text-primary truncate">
              {firstLine(commit.message)}
            </div>
          </button>

          <!-- Expanded Detail -->
          {#if isExpanded}
            <div class="px-4 pb-4 border-t border-border-default">
              {#if loadingDetail}
                <div
                  class="flex items-center gap-2 py-3 text-sm text-text-secondary"
                >
                  <div
                    class="w-4 h-4 border-2 border-border-default border-t-accent-emphasis rounded-full animate-spin"
                  ></div>
                  Loading detail...
                </div>
              {:else if detailError !== null}
                <div class="py-3 text-sm text-danger-fg">{detailError}</div>
              {:else if commitDetail !== null}
                <!-- Full hash -->
                <div class="py-3 space-y-3">
                  <div class="text-xs text-text-secondary">
                    <span class="font-mono select-all"
                      >{commitDetail.hash}</span
                    >
                  </div>

                  <!-- Full message -->
                  {#if commitDetail.body.trim().length > 0}
                    <div
                      class="text-sm text-text-primary whitespace-pre-wrap bg-bg-primary p-3 rounded border border-border-default"
                    >
                      {commitDetail.message}{commitDetail.body.trim().length > 0
                        ? "\n\n" + commitDetail.body
                        : ""}
                    </div>
                  {:else}
                    <div class="text-sm text-text-primary">
                      {commitDetail.message}
                    </div>
                  {/if}

                  <!-- Stats -->
                  <div class="flex items-center gap-4 text-xs">
                    <span class="text-text-secondary">
                      {commitDetail.stats.filesChanged} file{commitDetail.stats
                        .filesChanged !== 1
                        ? "s"
                        : ""} changed
                    </span>
                    <span class="text-success-fg"
                      >+{commitDetail.stats.additions}</span
                    >
                    <span class="text-danger-fg"
                      >-{commitDetail.stats.deletions}</span
                    >
                  </div>

                  <!-- Changed Files -->
                  {#if commitDetail.files.length > 0}
                    <div class="space-y-1">
                      <div
                        class="text-xs font-medium text-text-secondary uppercase tracking-wide"
                      >
                        Changed Files
                      </div>
                      <div
                        class="bg-bg-primary rounded border border-border-default divide-y divide-border-default"
                      >
                        {#each commitDetail.files as file (file.path)}
                          <div
                            class="flex items-center gap-2 px-3 py-2 text-xs"
                          >
                            <span class="font-medium {statusClass(file.status)}"
                              >{statusLabel(file.status)}</span
                            >
                            <span class="font-mono text-text-primary truncate"
                              >{file.path}</span
                            >
                            <div class="flex items-center gap-2 ml-auto shrink-0">
                              {#if file.additions > 0}
                                <span class="text-success-fg"
                                  >+{file.additions}</span
                                >
                              {/if}
                              {#if file.deletions > 0}
                                <span class="text-danger-fg"
                                  >-{file.deletions}</span
                                >
                              {/if}
                            </div>
                          </div>
                        {/each}
                      </div>
                    </div>
                  {/if}
                </div>
              {/if}
            </div>
          {/if}
        </div>
      {/each}

      <!-- Error banner (non-blocking, when we have some commits loaded) -->
      {#if error !== null && commits.length > 0}
        <div class="px-4 py-2 text-sm text-danger-fg bg-danger-subtle">{error}</div>
      {/if}

      <!-- Load More -->
      {#if hasMore}
        <div class="p-4">
          <button
            type="button"
            class="w-full px-4 py-2 text-sm border border-border-default rounded hover:bg-bg-tertiary transition-colors text-text-secondary"
            onclick={handleLoadMore}
            disabled={loadingMore}
          >
            {loadingMore ? "Loading..." : "Load More"}
          </button>
        </div>
      {/if}
    {/if}
  </div>
</div>

<style>
  @keyframes spin {
    to {
      transform: rotate(360deg);
    }
  }

  .animate-spin {
    animation: spin 1s linear infinite;
  }
</style>
